### ISSUE TITLE
What does it means when the lint is crossed out (strikethrough) ?

### ISSUE THREAD

**Issue by GilShoshan94** [dtolnay/noisy-clippy#17]
Hi David,

What does it mean when the lints are crossed out in your table ?

I could not find a clear explanation.
Are those the lints that used to be in the default and got downgraded to opt-in ?

**Comment by dtolnay** [comment]
Yes. They were downgraded out of the default lint set for being noisy or otherwise problematic.

**Comment by GilShoshan94** [comment]
Ok, thank you for the clarification.

Have a nice day.
